name: Linux Debug Integration Test Coverage

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: apt-deps
        run: sudo apt-get install gfortran lcov gcovr
      - name: configure_with_coverage
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DCOMMIT_SHA=aaaaaa$COMMIT_SHA -DBUILD_FORTRAN=ON -DBUILD_TESTING=ON -DENABLE_COVERAGE:BOOL=ON -DENABLE_GTEST_DEBUG_MODE:BOOL=OFF .. && cd ..
      - name: make
        run: make -j 3
        working_directory: ./build
#      - name: run_integration_tests
#        run: ctest -j 2 --timeout 4800 --no-compress-output -D ExperimentalTest -C Debug -R "integration.*"
#        working_directory: ./build
#      - name: run_lcov
#        run: lcov -c -d . -o ./lcov.output --no-external --base-directory ../src/EnergyPlus
#        working_directory: ./build
#      - name: filter_lcov
#        run: lcov -r ./lcov.output `pwd`/\\* -o ./lcov.output.filtered
#        working_directory: ./build
#      - name: generate_html
#        run: genhtml ./lcov.output.filtered -o lcov-html --demangle-cpp --function-coverage
#        working_directory: ./build
#      - name: tarball_coverage
#        run: tar -czvf integration_test_coverage.tar.gz lcov-html/
#        working_directory: ./build
#      - name: archive_coverage
#        uses: actions/upload-artifact@v1
#        with:
#          name: integration_test_coverage
#          path: build/integration_test_coverage.tar.gz
