name: Linux Custom Checks

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: custom_checks
        run: python3 scripts/dev/run_customchecks.py
