name: Linux Performance Testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: apt-deps
        run: sudo apt-get install gfortran valgrind ccache
      - name: run_builds
        run: bash .github/workflows/linux_performance.sh
      - name: archive_performance_results
        uses: actions/upload-artifact@v1
        with:
          name: performance_results
          path: results/
